spring:
  application:
    name: CONFIGCLIENT
  cloud:
    consul:
      port: 8500
      host: localhost
  rabbitmq:
    username: admin
    password: 123
    port: 5672
    host: localhost
name: test1111231231asdfs
